/* Brandooers · contenido personalizado por perfil (generado por el agente personalizador).
   Prueba de concepto (build-time). En el VPS esto lo generará una API en vivo para cualquier sector.
   Estructura: BOO_PERSONALIZATION[grupoSlot][preset] = { title?, desc?, hooks:[{title,msg}], practica } */
window.BOO_PERSONALIZATION = {
  "clientes": {
    "odoo": {
      "title": "Captar clientes para implantar Odoo",
      "desc": "Te diriges a pymes que llevan la operativa a trozos: presupuestos en un Excel, stock en otro, facturas en el programa del gestor y los pedidos en el correo. Nadie tiene la foto completa, cada cierre de mes es un puzle y ahora encima llega Verifactu. El dolor no es «no tener software», es tener cinco que no se hablan entre ellos y pagar por integraciones que se rompen. Muchos han pedido presupuesto a SAP o Sage y se han asustado con la cifra y con los plazos.",
      "hooks": [
        {"title": "El Excel maestro", "msg": "Hola [nombre], una pregunta directa: ¿seguís llevando [inventario/presupuestos] en Excel y pasándolo a mano al programa de facturación? Lo pregunto porque en [sector] es lo más común y suele ser justo donde se pierden horas y se cuelan errores. Si quieres te enseño en 15 minutos cómo lo tienen montado otras empresas parecidas a [empresa]. ¿Te viene bien esta semana?"},
        {"title": "Verifactu sin sustos", "msg": "Hola [nombre], con Verifactu ya en marcha, muchas empresas de [sector] están descubriendo que su facturación actual no cumple o depende de un parche del gestor. ¿Sabéis ya cómo lo vais a resolver en [empresa]? Si aún no lo tenéis cerrado, te cuento cómo se deja resuelto de forma que no dependas de nadie. ¿Hablamos 15 minutos?"},
        {"title": "El presupuesto de SAP", "msg": "Hola [nombre], me imagino que para una empresa como [empresa] ya os habrán pasado algún presupuesto de SAP o Sage y os habréis quedado a cuadros con el número y con los meses de implantación. Hay una alternativa que cubre lo mismo (ventas, stock, facturación, contabilidad) sin ese desembolso ni esos plazos. ¿Te enseño una demo con vuestro caso concreto?"},
        {"title": "Cinco programas, cero foto", "msg": "Hola [nombre], ¿cuántos programas distintos usáis ahora mismo en [empresa] para llevar el día a día? Cuando le hago esta pregunta a empresas de [sector] la respuesta suele ser «demasiados, y ninguno se habla con el otro». Trabajo justo eso: unificarlo todo en un sitio para que dejes de picar el mismo dato tres veces. ¿Te va bien que te lo enseñe el [día]?"}
      ],
      "practica": "Coge tu lista de clientes o de contactos de LinkedIn y quédate con 5 pymes de un mismo sector (por ejemplo distribución o fabricación). Míralas por encima: casi seguro que llevan la operativa con Excel más un facturador antiguo. Escríbeles hoy el gancho del «Excel maestro» adaptando [sector] y [empresa] a cada una. Cinco mensajes personalizados, no un copia-pega."
    },
    "ecommerce": {
      "title": "Captar clientes en el mundo ecommerce",
      "desc": "Te diriges a tiendas online y marcas DTC que venden bien pero se les escapa el margen por todos lados: la conversión no sube por mucho tráfico que metan, el 70% de los carritos se queda a medias, dependen de Amazon o de un solo canal de pauta que cada mes cuesta más, y las devoluciones se comen el beneficio. El dolor no es «vender poco», es que crecer les cuesta cada vez más caro y cualquier subida de stock, de CAC o de un cambio de algoritmo les descuadra la cuenta. Muchos viven con el miedo de depender de un marketplace que les puede cambiar las reglas mañana.",
      "hooks": [
        {"title": "El carrito abandonado", "msg": "Hola [nombre], he visto la tienda de [marca] y tengo una duda concreta: ¿estáis recuperando los carritos abandonados o esos pedidos se van sin más? En ecommerce suele ser el dinero más fácil de rescatar y casi nadie lo tiene bien montado. Si quieres te enseño en 15 minutos cómo se recupera una parte de eso sin tocar el producto ni bajar precios. ¿Te encaja esta semana?"},
        {"title": "Todo el huevo en Amazon", "msg": "Hola [nombre], veo que [marca] mueve bastante en Amazon. La pregunta incómoda: si mañana os suspenden la cuenta o os suben la comisión, ¿qué pasa con la facturación? Lo pregunto porque estoy ayudando a marcas parecidas a bajar esa dependencia y vender más por canal propio, donde el margen se queda entero. ¿Te cuento cómo lo estamos haciendo?"},
        {"title": "El CAC que no para de subir", "msg": "Hola [nombre], si la publicidad de [marca] cada mes cuesta más y convierte igual o peor, no sois los únicos: en 2026 el tráfico pagado está imposible. Trabajo justo eso, sacar más pedidos del tráfico que ya pagas antes de meter un euro más en pauta. ¿Te enseño por dónde suele estar la fuga en una tienda como la vuestra?"},
        {"title": "Devoluciones y reseñas", "msg": "Hola [nombre], una que veo mucho en marcas DTC: las devoluciones y las reseñas de una o dos estrellas se comen margen y confianza a la vez. ¿Tenéis medido cuánto os cuestan en [marca]? Si no, te enseño cómo verlo claro y reducirlo sin castigar la experiencia del cliente. ¿Hablamos 15 minutos esta semana?"}
      ],
      "practica": "Entra hoy en 5 tiendas online de tu nicho y haz el recorrido de compra completo: mete un producto al carrito, empieza el checkout y déjalo a medias. Fíjate en si te llega un email de recuperación, en cuántos pasos tiene el checkout y en si piden crear cuenta obligatoria. Ahí tienes tu gancho personalizado para cada una. Escribe el mensaje del «carrito abandonado» a la que peor lo tenga montado."
    },
    "servicios": {
      "title": "Captar clientes para tus servicios",
      "desc": "Te diriges a despachos, consultoras y agencias que hacen un trabajo excelente pero viven de los referidos y del boca a boca. El problema es la irregularidad: un trimestre están desbordados y el siguiente el pipeline está vacío, y no controlan cuándo llega el próximo cliente. Además les cuesta diferenciarse (todos dicen lo mismo en su web) y justificar un precio premium cuando el cliente compara solo por horas o por tarifa. Los ciclos son largos, la decisión la toman varias personas y una propuesta puede tardar meses en cerrarse. El dolor real es no tener un canal propio y predecible que no dependa de que alguien te recomiende.",
      "hooks": [
        {"title": "El pipeline en dientes de sierra", "msg": "Hola [nombre], una pregunta de las que no se hacen en voz alta: ¿sabéis en [despacho] de dónde va a salir el cliente del mes que viene, o depende de que os recomienden? Lo pregunto porque casi todos los despachos buenos que conozco viven en dientes de sierra, no por falta de calidad sino por no tener un canal propio. Si quieres te cuento cómo montar uno sin convertirte en un comercial pesado. ¿Hablamos 15 minutos?"},
        {"title": "Todos dicen lo mismo", "msg": "Hola [nombre], he entrado en la web de [despacho] y os pasa lo que a casi todo el sector: es difícil ver en tres segundos por qué elegiros a vosotros y no al de al lado. No es un problema de trabajo, es de posicionamiento. Ayudo justo a que ese «somos distintos» se note antes de la primera llamada, para que el cliente ya llegue medio convencido. ¿Te enseño un par de ejemplos?"},
        {"title": "Justificar el precio premium", "msg": "Hola [nombre], si en [despacho] os cuesta que el cliente entienda por qué valéis lo que valéis y acabáis compitiendo por tarifa, ese es justo el punto en el que trabajo. La clave no es bajar precio, es cómo se presenta el valor antes de hablar de números. ¿Te cuento el enfoque en una llamada corta esta semana?"},
        {"title": "Ciclos largos que se enfrían", "msg": "Hola [nombre], en servicios de alto valor el problema no suele ser conseguir la primera reunión, es que la propuesta se queda meses parada mientras deciden entre varios. ¿Os pasa en [despacho]? Trabajo cómo mantener vivo ese contacto sin perseguir al cliente, para que cuando decidan estéis vosotros arriba del todo. ¿Hablamos 15 minutos?"}
      ],
      "practica": "Haz una lista de tus últimos 10 clientes y anota de dónde vino cada uno. Si 8 de 10 llegaron por referido o boca a boca, ese es tu punto ciego: no tienes canal propio. Ahora coge 5 empresas de tu cliente ideal a las que te encantaría trabajar y que hoy no te conocen, y escribe a una el gancho del «pipeline en dientes de sierra» adaptando [despacho] al tipo de negocio que tengas. Empieza por proactividad, no por esperar."
    }
  }
};
